name: Security Auditing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  bandit:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r management/ setup/ tools/ -ll -s B108,B310,B324

  pip-audit:
    name: Dependency Vulnerability Audit (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pip-audit
          pip install dnspython3
          pip install rtyaml "email_validator>=1.0.0" exclusiveprocess flask dnspython python-dateutil expiringdict gunicorn defusedxml "qrcode[pil]" pyotp "webauthn>=2.7.0" "cbor2<6.0.0" "idna>=2.0.0" "cryptography>=44.0.2" psutil postfix-mta-sts-resolver b2sdk boto3

      - name: Run pip-audit
        run: pip-audit
